
name: Node CI

on:
  - push

jobs: 
  lint-my-code:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install eslint
      - run: eslint-config-airbnb-base
      - run: eslint-plugin-import
      - run: make install
      - run: make lint
      
    
